#!/usr/bin/env python3
"""Generate docs/diagrams/sentinel_system_context.pdf (first system-context diagram)."""

from __future__ import annotations

from pathlib import Path

import matplotlib.pyplot as plt
from matplotlib.patches import FancyArrowPatch, FancyBboxPatch


def _box(ax, x: float, y: float, w: float, h: float, text: str, *, fc: str, ec: str) -> None:
    p = FancyBboxPatch(
        (x, y),
        w,
        h,
        boxstyle="round,pad=0.015,rounding_size=0.08",
        linewidth=1.1,
        edgecolor=ec,
        facecolor=fc,
    )
    ax.add_patch(p)
    ax.text(x + w / 2, y + h / 2, text, ha="center", va="center", fontsize=9)


def _arrow(ax, x1: float, y1: float, x2: float, y2: float) -> None:
    a = FancyArrowPatch(
        (x1, y1),
        (x2, y2),
        arrowstyle="-|>",
        mutation_scale=12,
        linewidth=1.0,
        color="#37474F",
    )
    ax.add_patch(a)


def main() -> None:
    root = Path(__file__).resolve().parents[1]
    out = root / "docs" / "diagrams" / "sentinel_system_context.pdf"
    out.parent.mkdir(parents=True, exist_ok=True)

    fig, ax = plt.subplots(figsize=(8.5, 11))
    ax.set_xlim(0, 10)
    ax.set_ylim(0, 12)
    ax.axis("off")

    ax.text(5, 11.35, "Sentinel — system context", ha="center", fontsize=15, fontweight="bold")

    ax.text(1.0, 10.55, "Clients", fontsize=10, fontweight="bold", color="#1565C0")
    _box(ax, 0.5, 9.15, 4.0, 1.15, "Commissioning browser\n(/commissioning/*)", fc="#E3F2FD", ec="#1565C0")
    _box(ax, 5.5, 9.15, 4.0, 1.15, "Technician browser\n(/testing/{token})", fc="#E3F2FD", ec="#1565C0")

    ax.text(1.0, 8.55, "Edge (typical droplet)", fontsize=10, fontweight="bold", color="#E65100")
    _box(ax, 2.0, 7.35, 6.0, 0.95, "nginx :80  →  127.0.0.1:8000", fc="#FFF3E0", ec="#E65100")

    ax.text(1.0, 6.85, "Sentinel (Uvicorn / FastAPI)", fontsize=10, fontweight="bold", color="#2E7D32")
    _box(ax, 1.8, 5.55, 6.4, 1.0, "create_app()  ·  main.py", fc="#E8F5E9", ec="#2E7D32")

    ax.text(1.0, 5.05, "Persistence", fontsize=10, fontweight="bold", color="#6A1B9A")
    _box(ax, 0.6, 3.75, 4.0, 1.0, "PostgreSQL\n+ migrations", fc="#F3E5F5", ec="#6A1B9A")
    _box(ax, 5.4, 3.75, 4.0, 1.0, "InMemoryRepository\n(dev / tests)", fc="#F3E5F5", ec="#6A1B9A")

    ax.text(1.0, 3.25, "Local / server disk", fontsize=10, fontweight="bold", color="#455A64")
    _box(ax, 0.6, 1.85, 4.0, 1.0, "uploads\nSENTINEL_UPLOAD_ROOT", fc="#ECEFF1", ec="#455A64")
    _box(ax, 5.4, 1.85, 4.0, 1.0, "generated\nSENTINEL_GENERATED_ROOT\n*_project_data.json, HTML", fc="#ECEFF1", ec="#455A64")

    # Arrows (approx. box centers)
    _arrow(ax, 2.5, 9.15, 4.2, 8.3)
    _arrow(ax, 7.5, 9.15, 5.8, 8.3)
    _arrow(ax, 5.0, 7.35, 5.0, 6.55)
    _arrow(ax, 5.0, 5.55, 2.6, 4.75)
    _arrow(ax, 5.0, 5.55, 7.4, 4.75)
    _arrow(ax, 4.0, 5.55, 2.6, 2.85)
    _arrow(ax, 6.0, 5.55, 7.4, 2.85)

    fig.text(0.5, 0.35, f"Generated by {Path(__file__).name} — regenerate with: python devtools/render_sentinel_system_context_pdf.py", fontsize=7, color="#78909C")

    fig.savefig(out, format="pdf", bbox_inches="tight")
    plt.close(fig)
    print(out)


if __name__ == "__main__":
    main()
